module.exports = {
    env: {
      SANITY_DATASET_NAME: process.env.SANITY_DATASET_NAME,
      SANITY_PROJECT_ID: process.env.SANITY_PROJECT_ID,
      SANITY_DEFAULT_LANGUAGE: process.env.SANITY_DEFAULT_LANGUAGE,
      FIRESTORE_LOGIN: process.env.FIRESTORE_LOGIN,
      FIRESTORE_PASSWORD: process.env.FIRESTORE_PASSWORD
    }
  }